
[homeserver]
IP=192.168.178.27
HN=homeserver.fritz.box
SSH=root
LFTP=root

[pc]
IP=192.168.178.31
HN=pc.fritz.box
SSH=root
LFTP=root


[octo]
IP=192.168.178.35
HN=octoprint.fritz.box
SSH=root

[fritzbox]
IP=192.168.178.1
HN=fritz.box
SSH=root

[LibreElecSZ]
IP=192.168.178.52
HN=librelec.fritz.box
SSH=root

[Vero]
IP=192.168.178.64
HN=librelec.fritz.box
SSH=root

[rp3]
IP=192.168.178.73
HN=rp3.fritz.box
SSH=root

[pihole]
IP=192.168.178.199
HN=pihole.fritz.box
SSH=root